openapi: 3.0.0
info:
  title: Q-RICE API
  version: 1.0.0
paths:
  /api/rice-varieties:
    get:
      summary: Get Rice Varieties
      description: Retrieves a list of rice varieties.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
  
  /api/rice-diseases:
    get:
      summary: Get Rice Diseases
      description: Retrieves a list of rice diseases.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized

  /api/nutrient-deficiencies:
    get:
      summary: Get Nutrient Deficiencies
      description: Retrieves a list of nutrient deficiencies.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized
      
  /api/admin/users:
    get:
      summary: Get Users (Admin)
      description: Retrieves a list of users (admin only).
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized

  /api/admin/rice-varieties:
    post:
      summary: Create Rice Variety (Admin)
      description: Creates a new rice variety (admin only).
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Rice variety created successfully
        '401':
          description: Unauthorized
        '400':
          description: Invalid request payload

  /api/admin/rice-diseases:
    post:
      summary: Create Rice Disease (Admin)
      description: Creates a new rice disease (admin only).
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                symptoms:
                  type: string
      responses:
        '201':
          description: Rice disease created successfully
        '401':
          description: Unauthorized
        '400':
          description: Invalid request payload

  /api/admin/nutrient-deficiencies:
    post:
      summary: Create Nutrient Deficiency (Admin)
      description: Creates a new nutrient deficiency (admin only).
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                symptoms:
                  type: string
      responses:
        '201':
          description: Nutrient deficiency created successfully
        '401':
          description: Unauthorized
        '400':
          description: Invalid request payload

  /api/login:
    post:
      summary: User Login
      description: Authenticates the user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized


  /api/logout:
    post:
      summary: User Logout
      description: Logs out the user.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful logout
        '401':
          description: Unauthorized

  /api/register:
    post:
      summary: User Registration
      description: Registers a new user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: Successful registration
        '400':
          description: Invalid request payload

  /api/predict:
    post:
      summary: Image Prediction
      description: Predicts using an image.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                model:
                  type: string
                categoryId:
                  type: integer
                userId:
                  type: integer
      responses:
        '200':
          description: Successful prediction
        '401':
          description: Unauthorized
        '400':
          description: Invalid request payload
    get:
      summary: Get Prediction Histories
      description: Retrieves the prediction histories.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successful response
        '401':
          description: Unauthorized

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT